vim.keymap.set('v', '<Leader>/', ':Commentary<CR>', { noremap = true, silent = true })
vim.keymap.set('n', '<Leader>/', ':Commentary<CR>', { noremap = true, silent = true })
vim.keymap.set('n', '<Leader>csr', '"+y<CR>', { noremap = true, silent = true })
vim.keymap.set('v', '<Leader>csr', '"+y<CR>', { noremap = true, silent = true })
vim.keymap.set("n","<leader>pv", ':NvimTreeToggle<CR>')
vim.keymap.set("n","<leader>u", vim.cmd.UndotreeToggle)
vim.keymap.set("n","<F2>", ':FloatermToggle<CR>', { noremap = true, silent = true })
vim.keymap.set('n', 'tff', ':TerraformFmt<CR>', { noremap = true, silent = true })
vim.keymap.set("t","<F2>", "<C-\\><C-n>:FloatermToggle<CR>", { noremap = true, silent = true })

-- Other optional keybinds to init, validate, plan, apply (without approval!)
vim.keymap.set("n", "<leader>ti", ":!terraform init<CR>", { noremap = true, silent = true })
vim.keymap.set("n", "<leader>tv", ":!terraform validate<CR>", { noremap = true, silent = true })
vim.keymap.set("n", "<leader>tp", ":!terraform plan<CR>", { noremap = true, silent = true })
-- keymap("n", "<leader>taa", ":!terraform apply -auto-approve<CR>", opts)

